{
  description = "Homelab - 3-node NixOS k3s cluster (node0/node1/node2)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    # Secrets management: decrypts SOPS/age-encrypted secrets at build/activation
    sops-nix.url = "github:Mic92/sops-nix";
  };

  outputs = { self, nixpkgs, sops-nix, ... }:
    let
      system = "x86_64-linux";

      # Path to the SOPS-encrypted secrets file, resolved against the flake root
      # (NOT relative to a module file, which would break in the store).
      secretsFile = ./secrets/k3s-token.yaml;

      # Build one NixOS system per node. Each node imports its hand-tuned
      # configuration.nix (SSH, sudo, hostname, kernel, user) plus its
      # machine-specific hardware-configuration.nix (generated by nixos-generate-config)
      # plus the shared k3s module (enabled, all wired) + Tailscale + sops-nix.
      mkNode = hostName: nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = { inherit secretsFile; };
        modules = [
          ./hosts/${hostName}/configuration.nix
          ./hosts/${hostName}/hardware-configuration.nix
          ./modules/k3s.nix
          ./modules/tailscale.nix
          ./modules/ad.nix
          # sops-nix module: reads secrets/*.yaml on the node at activation
          sops-nix.nixosModules.sops
        ];
      };
    in
    {
      nixosConfigurations = {
        node0 = mkNode "node0";
        node1 = mkNode "node1";
        node2 = mkNode "node2";
      };
    };
}
