{
  description = "Homelab - 3-node NixOS k3s cluster (node0/node1/node2)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
  };

  outputs = { self, nixpkgs, ... }:
    let
      system = "x86_64-linux";

      # Build one NixOS system per node. Each node imports its hand-tuned
      # configuration.nix (SSH, sudo, hostname, kernel, user) plus its
      # machine-specific hardware-configuration.nix (generated by nixos-generate-config).
      mkNode = hostName: nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          ./hosts/${hostName}/configuration.nix
          ./hosts/${hostName}/hardware-configuration.nix
        ];
      };
    in
    {
      nixosConfigurations = {
        node0 = mkNode "node0";
        node1 = mkNode "node1";
        node2 = mkNode "node2";
      };
    };
}
