#ENC[AES256_GCM,data:nxBaKygroDuaVbZX1VvXNbGZ7FfUwVVOE2QiEt4UUSmO8hkwTsFBX8ymmM2iQlOdYTYj5Vg=,iv:168yFoJYstM4AWiG8H9EolDvGLup0YtNFV0hf8sTSM0=,tag:s/8CbHMvGukxE4Gmg6I6OA==,type:comment]
#ENC[AES256_GCM,data:4ZdQqO4/F+Crm8syKr7u8aqbKHxHBFV5OvrrzCzVMUGKCB50Hiyd73Y1cPpRbkVoMD4Yw7NqQPneYtmKYaCmBis6HGRB8LXw/TLPnDRZ,iv:dq3DudL68yC6ub0XVpK0GxbRYxxTJnhDp7nAU8wQPRY=,tag:gkH6kHBOZlY7UJ20RIYURw==,type:comment]
#ENC[AES256_GCM,data:QnbeFUtejEA+WMZSuJUm+WMdDlKc3GODQhNMQX+VGx4+Odcyzr6ICy7H6pXDIvtXym+4z18J+Go0bEQeAzDN9p4=,iv:DppQpFVbP/ozwD0PSP6umpwMHagg5KNbagUDmLbNVbk=,tag:QpcWDIsFOB9hO3uFggjGpA==,type:comment]
apiVersion: ENC[AES256_GCM,data:jQU=,iv:a8ZTCu+A0cXOnDgn4RSi650OUBp5h2VqVK11FEehitQ=,tag:uBeGedNNdebU0NYl42Z4Ww==,type:str]
kind: ENC[AES256_GCM,data:7ibRwctZ,iv:3RKr4fo0G7jCNMOJ8dt44jYT3cLYI3mdF4gF5urV1BI=,tag:AiGL6aQ3Ry8ghRtA4ABAnw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fLfjn6wOHm430WunpOlIm6j96bc=,iv:a+ZJFlAlhjoMAOl6wM+AvPdVW6CJPcf7PRYY2i8SfM8=,tag:OaHyS28Qz5Bi+Dwd4kNTQA==,type:str]
    namespace: ENC[AES256_GCM,data:WIt/8fmars7WTK+5V/lM,iv:SmaD9MYfeVgWwdcZDjHcElxnPp+zsfh0PQi9ZOb2rTw=,tag:DRQxIattYP4oPkL8GylKFg==,type:str]
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Oe7YK5fi5tgcpJ6utbQx5N42nB+6KYtcjg==,iv:heBgloojaKMi0fDiHJU6J8yWLWhspe1B9rfNGE1xj5o=,tag:qtNPAIZr+PnCAqIv6hvOng==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lhZq7NJZem4gdAyHH8YX4R4WlsJcHY2THXkJ3qH6yg==,iv:ejERNzwZtRREMJ+eXrKGsH/TDQVdICBR/LGaqTwHXYg=,tag:9RZqV+humI5MNJ2aBTeMTw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:QQkuhuNPwLHY7Rh9sVjUBlXD+f1DxRpID170ZVxzG3k2Nnbor3A=,iv:Y5szqRrgmKFNW81VPvNaioFUh9ILd1rY3hdCRKZHnAo=,tag:4w+cZLOxb+HGbM2ez5H9Xg==,type:str]
    VIRTUAL_HOSTED_STYLE: ENC[AES256_GCM,data:pBnR6Q==,iv:QEMmTEbfCYEWc6GpYojASZuIE5i4I4zbbY7lnH463zI=,tag:e4Rc3VMZH2+G03StMO71Qg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RmdaNzQ4M0RkRHdzdjdL
            dXhoUG54NnI4T3Z5aU95S1M4M3lLeXkydlM0CjZFZjRKTUtDVUFhbzNTNm5VZXNr
            eFJ5QlBld2dFVVlHR1JtL2YwRytnUHMKLS0tIHFhOWEwTVowbEVCN1VyUFZVL29T
            bDl1bnlSclZGN3FYWHkyVzdoMkRaN1UKyDVpGs6r9kExL5UdcHfWK1rx2bY0uHdY
            r/AS3kvjPWUTKgsYQXbjvCtTivZulHmbPlyaqsV2rPUnTl8QQIDw4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ywtmcludzu975w8j0csajllysn2frv6hdwwq74n575cjuytt5v9smtjfx5
    lastmodified: "2026-09-02T15:05:27Z"
    mac: ENC[AES256_GCM,data:GKK53sfjgVNQZBqm1WM7SzwLEA/eEvAYkQc9+qkpvttCWYRfJCyOdrOGwzzN5yZAuJQ1dla4bQwLz55RG/4fLHRfoVUHf9x1hbCESFH3z/A98rBWfml5pGpWZzK5bpE5u89hLhS0XBNzqJqkaGXckyLABUPTadCJjOKIMWmrbRQ=,iv:oApZpxy5GFthcljhLgDaibFT7qAIk58sPkOMAHEdUWI=,tag:ZpjBd+5j8EQjw6/3bknjYw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
